require:
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false